# helm/python-app/templates/servicemonitor.yaml
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "python-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
    release: prometheus
spec:
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "python-app.selectorLabels" . | nindent 6 }}
{{- end }}
